runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
env_variables:
  BUCKET_NAME: "voccosrg"
beta_settings:
  cloud_sql_instances: voccoservice:us-central1:voccotonydb=tcp:5432