-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgi/hbSwhSrtfxXlNV
9YNFFlz6z9YgXHTE+FmdnIMOjdSgCgYIKoZIzj0DAQehRANCAAR+dmER1yxIHupu
1qkZ4CA2vZ+opvh0hVo6R9Dm4jEUVXh8d3XRJBikM4ZBmVynsBWzKYpcjynm8RJn
6GYg4tic
-----END PRIVATE KEY-----