-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/Z63wDurf7gWUja7
4aVuEHWWjaj6bM6JOSTqajDfjWygCgYIKoZIzj0DAQehRANCAARTXeatekF6TDEy
6sxLrYD/3qvgXG8rKQNlhRXtkydEzEst/y9h+hRO3x8YSnuJ6ofmR62zH8GXlANm
Llpa9h6/
-----END PRIVATE KEY-----